#!/bin/bash
test(){
	
	${0%/*}/../bin/parse-diagram ${0%/*}/fixtures/$1.in.html > ${0%/*}/fixtures/$1.in.html.tmp
	diff -w ${0%/*}/fixtures/$1.out.txt ${0%/*}/fixtures/$1.in.html.tmp
	rm ${0%/*}/fixtures/$1.in.html.tmp
}

test 01-sample
test 02-sample




