#!/bin/bash
${0%/*}/../bin/parse-diagram ${0%/*}/fixtures/01-sample.in.html > ${0%/*}/fixtures/01-sample.in.html.tmp
diff -w ${0%/*}/fixtures/01-sample.out.txt ${0%/*}/fixtures/01-sample.in.html.tmp
rm ${0%/*}/fixtures/01-sample.in.html.tmp
